from bastionctl import cf_resources
import bastionctl.config as config
from troposphere import Template
from troposphere import GetAtt
from troposphere import Ref
from troposphere import Join
from troposphere import Output
import logging

logger = logging.getLogger(__name__)


# this can be genericised and placed into cf_resources module
def sg_ingress_allow_bastion_ip(bastion_ip, sg_ids):
    """
    Troposphere sg ingress rules helper
    """
    rules = []
    for i, sg_id in enumerate(sg_ids):
        rules.append(
            cf_resources.security_group_ingress(
                name='AllowBastion{}'.format(i),
                desc='Allow bastion (linux patching)',
                ip_protocol='tcp',
                from_port=22,
                to_port=22,
                group_id=sg_id,
                cidr=bastion_ip
            )
        )
    return rules


def sg_ingress_bastion(ips, sg_id):
    """
    """
    rules = []
    for i, ip in enumerate(ips):
        rules.append(
            cf_resources.security_group_ingress(
              name='BastionIngress{}'.format(i),
              desc='Allow bastion (linux patching)',
              ip_protocol='tcp',
              from_port=22,
              to_port=22,
              group_id=sg_id,
              cidr=ip
            )
        )
    return rules


def setup_bastion_stack_outputs(instance, vpc_id):
    """
    """
    outputs = []
    instance_id_key = config.stack_output_instance_id_key
    private_ip_key = config.stack_output_private_ip_key
    public_ip_key = config.stack_output_public_ip_key
    vpc_id_key = config.stack_output_vpc_id_key

    outputs.append(Output(
        instance_id_key,
        Description="Bastion instance id",
        Value=Ref(instance)
    ))
    outputs.append(Output(
        private_ip_key,
        Description="Bastion private Ip address",
        Value=GetAtt(instance, 'PrivateIp')
    ))
    outputs.append(Output(
        public_ip_key,
        Description="Bastion public Ip address",
        Value=GetAtt(instance, 'PublicIp')
    ))
    outputs.append(Output(
        vpc_id_key,
        Description="Bastion vpc id",
        Value=vpc_id
    ))

    return outputs


def create_bastion_template(name, ami_id, instance_type, key_name, subnet_id, vpc_id, bastion_sg_ingress, sg_ids):
    """
    Returns the  bastion cloudformation template
    """
    logger.info('generating bastion template')
    t = Template()
    t.add_description('Generated by infiniti ec2-patching cli')

    # setup our bastion security group and ec2 instance
    bastion_sg = cf_resources.security_group(
      name=name,
      desc=name,
      vpc_id=vpc_id
    )

    bastion_sg_ingress = sg_ingress_bastion(bastion_sg_ingress, Ref(bastion_sg))

    bastion_sg_egress_tcp_name = '{}-tcp-all'.format(name)
    bastion_sg_egress_tcp = cf_resources.security_group_egress(
      name=bastion_sg_egress_tcp_name,
      desc=bastion_sg_egress_tcp_name,
      ip_protocol='tcp',
      from_port='0',
      to_port='65535',
      group_id=Ref(bastion_sg),
      cidr='0.0.0.0/0'
    )

    bastion_sg_egress_udp_name = '{}-udp-all'.format(name)
    bastion_sg_egress_udp = cf_resources.security_group_egress(
      name=bastion_sg_egress_udp_name,
      desc=bastion_sg_egress_udp_name,
      ip_protocol='udp',
      from_port='0',
      to_port='65535',
      group_id=Ref(bastion_sg),
      cidr='0.0.0.0/0'
    )

    bastion_instance = cf_resources.ec2_instance(
      name=name,
      ami_id=ami_id,
      keyname=key_name,
      instance_type=instance_type,
      sg_ids=[Ref(bastion_sg)],
      subnet_id=subnet_id
    )

    # allow sg ingress to the bastion ip
    sg_ingress_bastion_ip = sg_ingress_allow_bastion_ip(
        bastion_ip=Join("", [GetAtt(bastion_instance, 'PrivateIp'), "/32"]),
        sg_ids=sg_ids
    )

    cf_resources.add_template_resources(
        template=t,
        resources=[
            bastion_sg,
            bastion_sg_ingress,
            bastion_sg_egress_tcp,
            bastion_sg_egress_udp,
            bastion_instance,
            sg_ingress_bastion_ip,
        ]
    )

    # setup the bastion stack outputs
    bastion_stack_outputs = setup_bastion_stack_outputs(bastion_instance, vpc_id)

    cf_resources.add_template_outputs(
        template=t,
        outputs=[
            bastion_stack_outputs
        ]
    )

    return t.to_yaml()
